### ISSUE TITLE
Build multi-person travel planning app 

### ISSUE THREAD

**Issue by Mellina05** [Mellina05/travel#5]
### `Planning` stage: create a plan for the trip, invite and communicate with friends
- [ ] Ability to create a `plan` **MH**

- [ ] Invite user by phone or email **MH**

- [ ] Communication features: **MH**

- chat functionality: multi-person chats 

- poll functionality: create a poll, publish poll results 

- feedback functionality: give feedback by reacting with emojis

- [ ] Notification feature **SH**

-  draft change

- reminder of upcomming trip

- [ ] `plan` version control **CH**

### `Travel` stage: view existing `plans`, share travel details

- [ ] `plan` offline mode **MH**

- [ ] Communication features:

- chat functionality with image share option **MH**

- share location **SH**

- [ ] Notification feature **SH**

- reminder up-comming trip

- weather notification

- apple watch notifications **NOT PLANNNED**

- [ ] Bookkeeping feature **SH**

- Receipt upload, and payer info

### `After-trip` stage: share and view `plan`

- [ ] Sharing feature - **availabe in all stages** **MH**

- share as PDF or image

- [ ] Notification feature

- End of trip reminder **MH**

- bookkeeping reminder **SH**

- [ ] Bookkeeping feature **SH**

- Calculate amount spent in trip, and how much each member should pay.
